import { ExperienceBar } from '@/components/ExperienceBar'
import { Profile } from '@/components/Profile'
import Head from 'next/head'

import styles from '../styles/pages/Home.module.css'
import { CompletedChallenges } from '@/components/CompletedChallenges'
import { Countdown } from '@/components/Countdown'

export default function Home() {
  return (
    <>
      <Head>
        <title>Move it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.container}>
        <ExperienceBar />

        <section>
          <div>
            <Profile />
            <CompletedChallenges />
            <Countdown />
          </div>

          <div></div>
        </section>
      </div>
    </>
  )
}
